# Template for /etc/kikimora/leshy/vpn.conf.
# install.sh creates the actual file from CLI flags or interactive input.

PRIMARY_INTERFACE="primary0"
PRIMARY_DEVICE_FILE="/run/kikimora/leshy/vpn/primary.dev"

SECONDARY_INTERFACE="secondary0"
SECONDARY_DEVICE_FILE="/run/kikimora/leshy/vpn/secondary.dev"
